version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: <image_repository/image_name>:latest
    container_name: code_editor_nebulaanish
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env